export const authTypes = {
  AUTH_UPDATE_LOGIN: 'AUTH_UPDATE_LOGIN',
  AUTH_UPDATE_PASSWORD: 'AUTH_UPDATE_PASSWORD',
  AUTH_RESET_LOGIN: 'AUTH_RESET_LOGIN',
  AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
  AUTH_SET_FAILED: 'AUTH_SET_FAILED',
  AUTH_RESET_FAILED: 'AUTH_RESET_FAILED',
  AUTH_RESET_PAGE: 'AUTH_RESET_PAGE',
};

export const appTypes = {
  APP_SET_LOADING: 'APP_SET_LOADING',
  APP_RESET_LOADING: 'APP_RESET_LOADING',
  APP_SET_USER: 'APP_SET_USER',
  APP_RESET_USER: 'APP_RESET_USER',
};

export const signUpTypes = {
  SIGNUP_SET_FIELD_VALUE: 'SIGNUP_SET_FIELD_VALUE',
  SIGNUP_SET_FIELDS_INVALID: 'SIGNUP_SET_FIELDS_INVALID',
  SIGNUP_RESET_FIELDS_INVALID: 'SIGNUP_RESET_FIELDS_INVALID',
  SIGNUP_RESET_PAGE: 'SIGNUP_RESET_PAGE',
};